### ISSUE TITLE
Exception has occurred: KeyError  'model.2.cv3.weight'

### ISSUE THREAD

**Issue by HANK538** [facerless/yolov5-tensorflow#1]
Hi 

请教一下  使用最新版的yolov5
转换过程中  发现权重名称形状不匹配

for var in vars:
        p=params_dict[var.name[:-2].replace("/",'.')]

Exception has occurred: KeyError
'model.2.cv3.weight'

有何步骤可以解这个问题呢
谢谢

**Comment by HANK538** [comment]
Hi

就算使用v3的pretrain模型转换还是会出现参数大小不吻合的情况

ValueError: Dimension 3 in both shapes must be equal, but are 27 and 255. Shapes are [1,1,320,27] and [1,1,320,255]. for 'Assign_663' (op: 'Assign') with input shapes: [1,1,320,27], [1,1,320,255].

**Comment by facerless** [comment]
修改class_num，确保class_num设置正确

**Comment by HANK538** [comment]
谢谢大神大大奉上星星
目前重train v3版本是可以转换成功

你的文章有提到使用ONNX
有一些坑需要注意的呢还是可以分享代码
我查一下都是转成Tensorflow2.0
有办法ONNX转1.13吗？
感谢

**Comment by HANK538** [comment]
大大再请问有试过1.13 tensorflow yolov5模型转成tflite吗？

**Comment by HANK538** [comment]
暫時沒問題了  謝謝
